### ISSUE TITLE
How to extract the widths of the curved lines from alluvial plots:

### ISSUE THREAD

**Issue by cmmertz** [corybrunson/ggalluvial#122]
Hi There! 
I have tried to extract the widths of the curved lines from an alluvial plot I generated using your tutorial but was unable to do so. Using the titanic voyager plot from your tutorial, say I wanted to know the width of the line that represents males from each class who survived the titanic. Any help in extracting data in this format is greatly appreciated! Thank you!

Here is a generic format of the code I tried but was unable to get to work:
# Build the ggplot object where p is the alluvial plot
p_build <- ggplot_build(p)

# Access the data
data <- p_build$data[[1]]  # Use the appropriate index if needed

# Filter the data based on the curve's color or any other criteria
filtered_data <- data[data$colour == "red", ]

# Extract the widths of the curved lines
line_widths <- filtered_data$size

**Comment by corybrunson** [comment]
Hi @cmmertz, sorry for taking a while to acknowledge this. I'm not completely sure i know what you want to calculate, but i've written some code below that hopefully at least puts you on the right track.

I have only rarely used `ggplot_build()` before, so this was a learning experience for me. My sense is that these data are more intuitive when the graphical objects being plotted more directly reflect the raw data, for example in a scatter plot. In this setting, the placement of alluvial objects is derived quite circuitously from the raw data, so backtracking that process to obtain plot information in terms of those original data is more of a challenge. (Note that, instead of calculating the difference between `ymax` and `ymin`, you could just extract the `prop` column for the percentage of the height taken up by each ribbon.)

Please do comment again if this is off the mark.

``` r
library(ggalluvial)
#> Loading required package: ggplot2

titanic_wide <- data.frame(Titanic)
p <- ggplot(data = titanic_wide,
       aes(axis1 = Class, axis2 = Sex, axis3 = Age,
           y = Freq)) +
  scale_x_discrete(limits = c("Class", "Sex", "Age"), expand = c(.2, .05)) +
  xlab("Demographic") +
  geom_alluvium(aes(fill = Survived)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_minimal() +
  ggtitle("passengers on the maiden voyage of the Titanic",
          "stratified by demographics and survival")

# recover the built plot
p_build <- ggplot_build(p)
# extract the data for the alluvium graphical objects
p_alluv <- p_build$data[[1L]]

# what are the survival colors
unique(p_alluv$fill)
#> [1] "#F8766D" "#00BFC4"
# filter to males and survivors
p_alluv_male_surv <-
  p_alluv[p_alluv$stratum == "Male" & p_alluv$fill == "#00BFC4", ]
# remove (redundant) stratum column (to avoid confusion in merge)
p_alluv_male_surv <- subset(p_alluv_male_surv, select = -stratum)

# filter to class data for survivors
p_alluv_class_surv <-
  p_alluv[p_alluv$x == 1 & p_alluv$fill == "#00BFC4", ]
# select only alluvia (by which to merge) and class
p_alluv_class_surv <- p_alluv_class_surv[, c("alluvium", "stratum")]
# merge class data into male survivor data
p_alluv_male_surv <-
  merge(p_alluv_male_surv, p_alluv_class_surv, by = "alluvium")

# calculate ribbon heights
p_alluv_male_surv$height <- p_alluv_male_surv$ymax - p_alluv_male_surv$ymin
# restrict to class strata and ribbon heights
p_alluv_male_surv <- subset(p_alluv_male_surv, select = c(stratum, height))
# add heights within strata (combine adult and child counts)
aggregate(
  p_alluv_male_surv$height,
  by = subset(p_alluv_male_surv, select = stratum),
  FUN = sum
)
#>   stratum   x
#> 1     1st  62
#> 2     2nd  25
#> 3     3rd  88
#> 4    Crew 192
```

<sup>Created on 2023-10-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by corybrunson** [comment]
@cmmertz hopefully this is resolved, but please do reopen the issue if not, or if you have follow-up questions!
