### ISSUE TITLE
could not find function "fill_alpha"

### ISSUE THREAD

**Issue by ninghaitao** [corybrunson/ggalluvial#127]
When I run the case on the official website, the following problem is displayed. 

Error in fill_alpha(data$fill %||% "grey20", data$alpha) : 
  could not find function "fill_alpha"

My ggplot2 version is 3.4.4，ggalluvial version is 0.12.5

**Comment by corybrunson** [comment]
Hi @ninghaitao, thanks for raising the issue. This might be a {ggplot2} issue rather than a {ggalluvial} one, since `fill_alpha` is part of that package (see documentation [here](https://ggplot2.tidyverse.org/reference/fill_alpha.html)). I'll try using those two versions within a couple of days. I can check more carefully if you post here (or point me to) the specific example you're using that still presents the problem.

**Comment by corybrunson** [comment]
Hi @ninghaitao, i have those versions of {ggplot2} and {ggalluvial} installed and i don't get the same error when running the examples on the README (i.e. those presented [here](https://github.com/corybrunson/ggalluvial)). This might be an issue with a dependency. As you have time, perhaps update all of your packages and see if the problem persists.

**Comment by ninghaitao** [comment]
@corybrunson Thank you very much for taking the time to reply to my message. I will try to update the software package again.

**Comment by ninghaitao** [comment]
@corybrunson I solved the problem by updating all packages, thanks again

**Comment by Haibara0422** [comment]
> @corybrunson I solved the problem by updating all packages, thanks again

Hello, my ggplot2 and ggalluvial version is the same as yours and I also meet this problem now, did you solve this problem just by updating the version, thx!

**Comment by corybrunson** [comment]
@Haibara0422 the problem seems to have been solved by updating other packages. You can update all installed packages using `remotes::update_packages()`.
