### ISSUE TITLE
Add community guidelines for contributing/reporting

### ISSUE THREAD

**Issue by tweed1e** [corybrunson/ggalluvial#48]
The JOSS code review requires (https://github.com/openjournals/joss-reviews/issues/2017):

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I know you mention these in the README.md, but there could also be a specific CONTRIBUTING.md file.

I'm not sure what the best practice is (it seems like github has features that suggest its own community guidelines, etc.) but here is an example I found for R from ropensci+JOSS: https://github.com/ropensci/dotgithubfiles

There may be more recent examples or better practices as well.

**Comment by corybrunson** [comment]
I've vacillated on this and it's probably good to be prompted to go ahead with it. Since this is a ggplot2 extension, i'll adapt a `CONTRIBUTING.md` file from theirs ([here](https://github.com/tidyverse/ggplot2/blob/master/CONTRIBUTING.md)), though since it'll be shorter i'm glad to have the ropensci one as a point of reference. (I also haven't come across any widely-used best practice.) Thanks! I'll get to this today or tomorrow.

**Comment by corybrunson** [comment]
The most recent commit to `master` (01aead6776440b27664d5cd20a1f16663fa32c4e) includes `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md`, both loosely adapted from the sources mentioned here. Please let me know if you think they could be improved!
