### ISSUE TITLE
link to vignettes in object documentation

### ISSUE THREAD

**Issue by jasonpott** [corybrunson/ggalluvial#61]
### Description of the issue
When viewing ?geom_stratum the help file is missing some of the detail of the the functionality available within the [packagedown page ](https://corybrunson.github.io/ggalluvial/articles/order-rectangles.html)

This is a non-urgent issue and has no impact on usability.

I wondered whether I might make the suggestion that some of the information recorded in your packagedown page might be included in the help files within the package e.g. decreasing and reverse. 

I'm not sure of the etiquette for making suggestions such as this should I include suggested edits to the help file?

**Comment by corybrunson** [comment]
Oh, good question. Since this isn't a bug, i think it's fine to free-form your issue—and i'll update the template to say that!

I think the first issue is the same as #60, which i think has been resolved. Can you access the page now?

Could you say what from the website would be useful in the package documentation? Most of the content, including the "articles" should be installed with the package and viewable using the `vignette()` function. For example, the article linked above should appear if you execute the following in an R session:
```r
vignette(topic = "order-rectangles", package = "ggalluvial")
```
To get a list of vignettes from a specific package, do this:
```r
vignette(package = "ggalluvial")
```
Do these work for you?

**Comment by jasonpott** [comment]
Yes the package down page is working fine now. (thank you)!

I should have used the vigette functionality (I had seen it used but it was not in my muscle memory). I have tried the vignettes and they work well and present the same info as the packagedown site. I will remember to look to these in future.

The arguments section of the help file presents the following parameters :

mapping 
data 
stat
position 
show.legend 
inherit.aes 
width 
... | Additional arguments passed to ggplot2::layer().

The vignette for order-rectangles is a good document to point to here as well but does not need to be replicated. I can't see anything in the help file  for ?geom_stratum that points to it. 

In terms of customising the output of the geom it is a really good reference but people who are newer to R (like me) may not find it. 

If internal links are possible it would be helpful to add one to that ?geom_strata help file and I imagine similarly the help files for alluvium, flow, and lode may benefit.

**Comment by corybrunson** [comment]
Oh, that's a good suggestion! I'll make sure to include links (or else code to access them) in the documentation with the next release.

**Comment by corybrunson** [comment]
The `doc-vig` branch was at first an attempt to incorporate these links, but the only ways to do this appear to be pretty hacky. Since a case could be make to link to one or more vignettes from every plot layer, instead now all the vignettes are mentioned and described in the README, which seems like a better way to make sure every user knows when they might want to use them. (I'd be glad to know if this might not be right.)
